mod artifact;
mod bootstrap;
mod compiler;
mod config;
mod host;
mod model;
mod prompt;
mod reducer;
mod status;
mod tools;

pub use bootstrap::Feature;
pub use bootstrap::InitError;
pub use bootstrap::SpineRegistration;
pub use bootstrap::SpineRegistrationBuilder;
pub use compiler::SpineCompiler;
pub use compiler::SpineError;
pub use config::SpineConfig;
pub use host::HostStep;
pub use host::RuntimeError;
pub use host::RuntimeProjection;
pub use host::SpineHost;
pub use host::SpineOutput;
pub use host::SpineRuntime;

pub use model::ContextEdit;
pub use model::ContextItem;
pub use model::MemorySlot;
pub use model::Message;
pub use model::MessageRole;
pub use model::NativeItemRef;
pub use model::NodeId;
pub use model::NodeKind;
pub use model::NodeSnapshot;
pub use model::NodeStatus;
pub use model::ProjectionDelta;
pub use model::RawBoundary;
pub use model::RawSpan;
pub use model::RolloutEvent;
pub use model::SPINE_SPAWN_RESULT_SCHEMA;
pub use model::SpawnOutcome;
pub use model::SpawnReceipt;
pub use model::SpawnResult;
pub use model::SpawnTask;
pub use model::SpawnValidationError;
pub use model::SpineProjection;
pub use model::ToolCallGroup;
pub use model::ToolOutcome;
pub use model::ToolUse;
pub use model::TrimEdit;
pub use model::TrimOperation;
pub use model::TrimProjection;
pub use model::TrimRequest;
pub use model::TrimSlice;
pub use reducer::TOOL_RESPONSE_TRIM_THRESHOLD_BYTES;
pub use tools::ToolCatalog;

#[cfg(test)]
mod tests;
