mod artifact;
mod bootstrap;
mod compiler;
mod config;
mod context_char;
mod event;
mod host;
mod model;
mod prompt;
mod reducer;
mod status;
mod tools;

pub use bootstrap::InitError;
pub use compiler::MAX_RAW_EVENT_BYTES;
pub use compiler::MAX_SYNTHETIC_CONTEXT_BYTES;
pub use compiler::MAX_TREE_NODES;
pub use compiler::MAX_VISIBLE_CONTEXT_ITEMS;
pub use compiler::SpineCompiler;
pub use compiler::SpineError;
pub use config::ConfigError;
pub use config::DEFAULT_CONFIG_TOML;
pub use config::Feature;
pub use config::SpineConfig;
pub use context_char::CharParseError;
pub use context_char::CharParseStep;
pub use context_char::ParseStack;
pub use context_char::SpineChar;
pub use context_char::SpineCharParser;
pub use context_char::ToolRequestChar;
pub use context_char::ToolResponseChar;
pub use event::ContextTransition;
pub use event::HandlerCardinality;
pub use event::SpineEventHandlers;
pub use event::SpineObserverCause;
pub use event::SpineObserverEvent;
pub use event::SpineTransitionEvent;
pub use host::HostStep;
pub use host::RuntimeError;
pub use host::RuntimeProjection;
pub use host::SpineHost;
pub use host::SpineOutput;
pub use host::SpineRuntime;

pub use artifact::MemoryArtifact;
pub use artifact::TRIM_SNIPPED_BODY;
pub use artifact::UserMessageArtifact;
pub use artifact::closed_memory_artifacts;
pub use artifact::render_memory_artifact;
pub use model::ContextEdit;
pub use model::ContextItem;
pub use model::MemorySlot;
pub use model::Message;
pub use model::MessageRole;
pub use model::NativeItemRef;
pub use model::NodeId;
pub use model::NodeKind;
pub use model::NodeSnapshot;
pub use model::NodeStatus;
pub use model::ProjectionDelta;
pub use model::RawBoundary;
pub use model::RawSpan;
pub use model::RolloutEvent;
pub use model::SPINE_SPAWN_RESULT_SCHEMA;
pub use model::SpawnOutcome;
pub use model::SpawnReceipt;
pub use model::SpawnResult;
pub use model::SpawnTask;
pub use model::SpawnValidationError;
pub use model::SpineProjection;
pub use model::ToolCallGroup;
pub use model::ToolOutcome;
pub use model::ToolUse;
pub use model::TrimEdit;
pub use model::TrimOperation;
pub use model::TrimProjection;
pub use model::TrimRequest;
pub use model::TrimSlice;
pub use reducer::TOOL_RESPONSE_TRIM_THRESHOLD_BYTES;
pub use status::ContextPressure;
pub use status::ContextPressureProblem;
pub use status::StatusSignal;
pub use status::TokenUsageSample;
pub use status::TreeNode;
pub use status::TreeSnapshot;
pub use status::context_pressures;
pub use status::status_signal;
pub use status::tree_snapshot;
pub use tools::MAX_MEMORY_BYTES;
pub use tools::MAX_SPAWN_BATCH_BYTES;
pub use tools::MAX_SPAWN_PROMPT_BYTES;
pub use tools::MAX_SPAWN_TASKS;
pub use tools::MAX_SUMMARY_BYTES;
pub use tools::SPINE_NAMESPACE;
pub use tools::SPINE_NAMESPACE_DESCRIPTION;
pub use tools::SpineTool;
pub use tools::ToolCatalog;
pub use tools::ToolDefinition;
pub use tools::ToolValidation;
pub use tools::ToolValidationError;
pub use tools::ValidatedTransition;
pub use tools::success_carrier;
pub use tools::validate_tool;

#[cfg(test)]
mod tests;
